image: alpine:latest

variables:
  CODE_QUALITY_DISABLED: "true"
  CONTAINER_SCANNING_DISABLED: "true"
  DAST_DISABLED: "true"
  DEPENDENCY_SCANNING_DISABLED: "true"
  LICENSE_MANAGEMENT_DISABLED: "true"
  PERFORMANCE_DISABLED: "true"
  SAST_DISABLED: "true"
  ROLLOUT_RESOURCE_TYPE: deployment
  POSTGRES_ENABLED: "false"
  PRODUCTION_ADDITIONAL_HOSTS: mavenanalytics.io,www.mavenanalytics.io
  K8S_SECRET_SENTRY_ENVIRONMENT: $CI_COMMIT_REF_NAME

stages:
  - build
  - test
  - deploy # dummy stage to follow the template guidelines
  - review
  - dast
  - staging
  - canary
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup

include:
  - template: Jobs/Build.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab-foss/blob/master/lib/gitlab/ci/templates/Jobs/Build.gitlab-ci.yml
  - template: Jobs/Test.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab-foss/blob/master/lib/gitlab/ci/templates/Jobs/Test.gitlab-ci.yml
  - template: Jobs/Deploy.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab-foss/blob/master/lib/gitlab/ci/templates/Jobs/Deploy.gitlab-ci.yml

staging_deploy:
  extends: .auto-deploy
  stage: staging
  before_script: 
    - export K8S_SECRET_SENTRY_ENVIRONMENT=staging
    - export K8S_SECRET_HOST_API=http://staging-auto-deploy.api-15461716-staging.svc.cluster.local:5000
    - export K8S_SECRET_GATEWAY=http://staging-auto-deploy.gateway-15469306-staging.svc.cluster.local:5000  
  script:
    - auto-deploy check_kube_domain
    - auto-deploy download_chart
    - auto-deploy ensure_namespace
    - auto-deploy initialize_tiller
    - auto-deploy create_secret
    - auto-deploy deploy
  environment:
    name: staging
    url: https://staging.$KUBE_INGRESS_BASE_DOMAIN
  only:
    refs:
      - staging

stop_staging:
  extends: .auto-deploy
  stage: cleanup
  variables:
    GIT_STRATEGY: none
  script:
    - auto-deploy initialize_tiller
    - auto-deploy delete
  environment:
    name: staging
    action: stop
  when: manual
  allow_failure: true
  only:
    refs:
      - staging
