apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - name: {{ .Values.app.name }}
          containerPort: 5000
        livenessProbe:
          httpGet:
            path: /-/liveness
            scheme: "HTTP"
            port: 5000
          initialDelaySeconds: 15
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /-/readiness
            scheme: "HTTP"
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 15
        envFrom:
          - secretRef:
              name: {{ .Values.application.secretName }}
        env:
          - name: GITLAB_ENVIRONMENT_NAME
            value: {{ .Values.gitlab.envName }}
          - name: GITLAB_ENVIRONMENT_URL
            value: {{ .Values.gitlab.envURL }}
